### ISSUE TITLE
Ошибка при попытке войти в административную часть

### ISSUE THREAD

**Issue by EijiMirai** [konjoot/rails_admin_flatly_theme#10]
```
Showing /usr/local/rvm/gems/ruby-2.1.5@rails4/gems/rails_admin-0.6.5/app/views/layouts/rails_admin/application.html.haml where line #7 raised:
File to import not found or unreadable: bootstrap/variables.
```

Вот такая ошибка возникла.
Видимо ему не хватает файла с переменными бутстрапа, но почему его нет - для меня остаётся тайной.

**Comment by konjoot** [comment]
Приветствую, это в development окружении?

**Comment by jFoxSingularity** [comment]
Да, именно там.

**Comment by konjoot** [comment]
Спасибо, что обратили внимание, отправил фикс в мастер, в общем ситуация следующая - поддерживается пока только RailsAdmin < 0.6.6, как будет время доработаю тему, для версии 0.6.6.
