### ISSUE TITLE
Precompile error

### ISSUE THREAD

**Issue by EijiMirai** [konjoot/rails_admin_flatly_theme#9]
`rake assets:precompile` return [error](https://gist.github.com/jFoxSingularity/4ae70e0ace50437d3d16)

**Comment by konjoot** [comment]
Thanks for feedback, I'll check this issue in near time.

**Comment by denysnando** [comment]
I'm with the same error, what should I do?

**Comment by konjoot** [comment]
This problem was fixed in master, in your Gemfile, please, replace string, related to  flatly_theme, by this:

      gem 'rails_admin_flatly_theme', github: 'konjoot/rails_admin_flatly_theme'

And run `bundle`

**Comment by denysnando** [comment]
fix the problem using the version

gem 'rails_admin', '0.6.5'

**Comment by konjoot** [comment]
Thank you for feedback, can you tell what version of RailsAdmin you were using before?

**Comment by denysnando** [comment]
before was using 0.6.6
